<div class="bg-dark text-white"><h2 class="text-danger text-center">WORKLOAD</h2></div>
<div>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ENTRY </th>
      <th scope="col">TITLE </th>
      <th scope="col">NOTES </th>
      <th scope="col">STATUS</th>
      <th scope="col">ACTION</th>
    </tr>
  </thead>

<?php foreach ($this->posts as $post): ?>
  <tbody>
    <tr>
      <th scope="row"><?= $post->getId()?></th>
      <td><?= $post->getTitle() ?></td>
      <td><?= $post->getText() ?></td>
      <td><input type="checkbox" class="form-check-input center" id="exampleCheck1" checked>
      <td>
      <button type="button" class="btn btn-warning">Edit</button>
      <button type="button" class="btn btn-danger">Delete</button></td>
     
    </tr>
  </tbody>


<?php endforeach ?>
</table>
</div>